version: '3.8'
# setting up docker image log rotation 
x-log: &logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "10"

services:
  vpn:
    <<: *logging
    image: coralhl/vipnetclient:debian
    container_name: vipnet-client
    env_file:
      - ./.env
    restart: unless-stopped
    privileged: true
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - HEALTHCHECK_CMD=$HEALTHCHECK_CMD
      - DNS_SERVER=77.88.8.88,77.88.8.2
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ./app/key.dst:/vipnet/key.dst
      - ./app/data/:/vipnet/
    healthcheck:
      test: ${HEALTHCHECK_CMD}
      interval: 30s
      timeout: 10s
      retries: 10